# Generated by Django 2.2 on 2019-04-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('ranking', models.CharField(default='', max_length=3, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=20)),
                ('personnel_info', models.CharField(default='', max_length=50)),
                ('year', models.CharField(default='', max_length=4)),
                ('country', models.CharField(default='', max_length=10)),
                ('type', models.CharField(default='', max_length=40)),
                ('score', models.CharField(default='', max_length=4)),
                ('num', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
