# Generated by Django 2.2 on 2019-04-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayTalk',
            fields=[
                ('airtime', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('thumb', models.ImageField(default='', max_length=200, upload_to='')),
                ('url', models.URLField(default='', max_length=100)),
            ],
        ),
    ]
