# Generated by Django 2.2 on 2019-04-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_todaytalk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaytalk',
            name='thumb',
        ),
    ]
