# Generated by Django 2.2 on 2019-04-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_remove_todaytalk_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='JDGoodsInfo',
            fields=[
                ('title', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('price', models.URLField(default='', max_length=10)),
                ('commit', models.URLField(default='', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='TodayTalk',
        ),
    ]
